// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hooxsyupdsfumygmayni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhvb3hzeXVwZHNmdW15Z21heW5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExOTExNjUsImV4cCI6MjA2Njc2NzE2NX0.y3joytqHHFLmGu3A9qx0vldqfsyRt58LrWJqlpWn8W4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);